name: manual-release

on:
  workflow_dispatch:
    inputs:
      hc_version:
        description: 'holochain version'
        required: true

jobs:

  call-build:
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      discussions: write
      issues: write
      packages: write
      pages: write
      pull-requests: write
      repository-projects: write
      statuses: write
      security-events: write
      id-token: write
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      hc-version: '${{ github.event.inputs.hc_version }}'
      upload-tag: "manual-release"
