name: Release

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: taiki-e/create-gh-release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    permissions: write-all
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      # Checkout holochain repo
      - name: Checkout holochain repo
        run: git clone --depth 1 --branch holochain-0.1.0 https://github.com/holochain/holochain.git
      # Build hc
      - name: Build hc
        env:
          FIX_SQL_FMT: 1         
        run: cargo build --release --manifest-path ./holochain/crates/hc/Cargo.toml
      # list release folder
      - name: list release folder
        run: ls
        working-directory: holochain/target/release
      # upload binary for each platform
      - name: Compress binary
        if: ${{ runner.os == 'Linux' }}
        uses: a7ul/tar-action@v1.1.0
        id: compress
        with:
          command: c
          cwd: ./
          files: |
            ./holochain/target/release/hc
          outPath: hc_linux.tar.gz
      # upload binary for each platform
      - name: upload binary (ubuntu only)
        if: ${{ runner.os == 'Linux' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cp ./holochain/target/release/hc hc_linux
          gh release upload "${GITHUB_REF#refs/tags/}" "hc_linux" --clobber
      - name: upload binary (macos only)
        if: ${{ runner.os == 'macOs' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cp ./holochain/target/release/hc hc_mac
          gh release upload "${GITHUB_REF#refs/tags/}" "hc_mac" --clobber
      - name: upload binary (Windows only)
        if: ${{ runner.os == 'Windows' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "${GITHUB_REF#refs/tags/}" "./holochain/target/release/hc.exe" --clobber
