name: Release

on:
  push:
    tags:
      - '[0-9]+.*'

jobs:
  upload-assets:
    permissions: write-all
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: GitHub Tag Name test
        run: |
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "Tag name from env.GITHUB_REF_NAME: ${{env.GITHUB_REF_NAME}}"          
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"
          echo "runner.os: ${{  runner.os }}"
      # Checkout holochain repo
      - name: Checkout holochain repo
        run: git clone --depth 1 --branch holochain-${{  github.ref_name }} https://github.com/holochain/holochain.git
      # Build hc
      - name: Build hc
        env:
          FIX_SQL_FMT: 1
        run: cargo build --release --manifest-path ./holochain/crates/hc/Cargo.toml
      # list release folder
      - name: list release folder
        run: ls
        working-directory: holochain/target/release
      # Compress binary for each platform
      - name: Compress binary
        if: ${{ runner.os == 'Linux' }}
        uses: a7ul/tar-action@v1.1.2
        with:
          command: c
          files: |
            ./holochain/target/release/hc
          outPath: hc_${{  runner.os }}.tar.gz
      - name: Compress binary
        if: ${{ runner.os == 'macOs' }}
        uses: a7ul/tar-action@v1.1.2
        with:
          command: c
          files: |
            ./holochain/target/release/hc
          outPath: hc_${{  runner.os }}.tar.gz
      - name: Compress binary
        if: ${{ runner.os == 'Windows' }}
        uses: a7ul/tar-action@v1.1.2
        with:
          command: c
          files: |
            ./holochain/target/release/hc.exe
          outPath: hc_windows.tar.gz
      # upload binary for each platform
      - name: upload binary (ubuntu-mac only)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "${{  github.ref_name }}" "hc_${{  runner.os }}.tar.gz" --clobber
