name: Release

on:
  push:
    tags:
      - '[0-9]+.*'

jobs:
  call-build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      hc-version: '${{  github.ref_name }}'
      upload-tag: '${{  github.ref_name }}'
