name: test-release

on: workflow_dispatch

jobs:
  upload-assets:
    permissions: write-all
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: NPM Setup
        if: ${{ runner.os == 'Windows' }}
        shell: bash
        run: |
          npm config set script-shell "C:\\Program Files\\git\\bin\\bash.exe"
      # Test config
      - name: print-config
        shell: bash
        run: |
          npm run print-config
      # Checkout holochain repo
      - name: Checkout holochain repo
        run: git clone --depth 1 --branch holochain-0.1.3 https://github.com/holochain/holochain.git
      # Build hc
      - name: Build hc
        env:
          FIX_SQL_FMT: 1
        run: cargo build --release --manifest-path ./holochain/crates/hc/Cargo.toml
      # list release folder
      - name: list release folder
        run: ls
        working-directory: holochain/target/release
      # Test scripts
      - name: install:hc-cli
        shell: bash
        run: |
          npm run install:hc-cli
      - name: version
        shell: bash
        run: |
          npm run version
      # Compress binary for each platform
      - name: Compress binary (unix)
        if: ${{ runner.os == 'Linux' || runner.os == 'macOs' }}
        uses: a7ul/tar-action@v1.1.2
        with:
          command: c
          files: |
            ./holochain/target/release/hc
          outPath: hc_${{  runner.os }}.tar.gz
      - name: Compress binary (windows)
        if: ${{ runner.os == 'Windows' }}
        uses: a7ul/tar-action@v1.1.2
        with:
          command: c
          files: |
            ./holochain/target/release/hc.exe
          outPath: hc_${{  runner.os }}.tar.gz
      # list root folder
      - name: list root folder
        run: ls
        working-directory: ./
      # upload binary for each platform
      - name: upload binary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "manual-release" "hc_${{  runner.os }}.tar.gz" --clobber     
