name: test-release

on: workflow_dispatch

jobs:
  upload-assets:
    permissions: write-all
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      # Checkout holochain repo
      - name: Checkout holochain repo
        run: git clone --depth 1 --branch holochain-0.1.3 https://github.com/holochain/holochain.git
      # Build hc
      - name: Build hc
        env:
          FIX_SQL_FMT: 1
        run: cargo build --release --manifest-path ./holochain/crates/hc/Cargo.toml
      # list release folder
      - name: list release folder
        run: ls
        working-directory: holochain/target/release
      # Compress binary for each platform
      - name: Compress binary
        if: ${{ runner.os == 'Linux' }}
        uses: a7ul/tar-action@v1.1.2
        with:
          command: c
          files: |
            ./holochain/target/release/hc
          outPath: hc_${{  runner.os }}.tar.gz
      - name: Compress binary
        if: ${{ runner.os == 'macOs' }}
        uses: a7ul/tar-action@v1.1.2
        with:
          command: c
          files: |
            ./holochain/target/release/hc
          outPath: hc_${{  runner.os }}.tar.gz
      - name: Compress binary
        if: ${{ runner.os == 'Windows' }}
        uses: a7ul/tar-action@v1.1.2
        with:
          command: c
          files: |
            ./holochain/target/release/hc.exe
          outPath: hc_${{  runner.os }}.tar.gz
      # upload binary for each platform
      - name: upload binary (ubuntu only)
        if: ${{ runner.os == 'Linux' || runner.os == 'macOs'}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cp ./holochain/target/release/hc hc_${{  runner.os }}
          gh release upload "manual-release" "hc_${{  runner.os }}" --clobber
          gh release upload "manual-release" "hc_${{  runner.os }}.tar.gz" --clobber
      - name: upload binary (Windows only)
        if: ${{ runner.os == 'Windows' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "manual-release" "hc_${{  runner.os }}.tar.gz" --clobber          
          gh release upload "manual-release" "./holochain/target/release/hc.exe" --clobber
